from __future__ import annotations

from pathlib import Path
import pandas as pd


REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_DIR = REPO_ROOT / "data" / "processed" / "outputs"


# Source file generated by your pipeline
WEB_TOP10_PATH = OUTPUT_DIR / "web_current_top10.csv"

# Canva outputs
CANVA_TOP5_PATH = OUTPUT_DIR / "canva_top5_flat.csv"
CANVA_6_10_PATH = OUTPUT_DIR / "canva_6_10_flat.csv"


# Fields we want from web_current_top10
# (Matches your header row)
STAT_FIELDS = {
    "name": "player_name",
    "team": "team",
    "gp": "games_played",
    "ppg": "pts",
    "rpg": "trb",
    "apg": "ast",
    "spg": "stl",
    "bpg": "blk",
    "chips": "chips",
}


def _flatten(df: pd.DataFrame, ranks: list[int], prefix_map: dict[int, str]) -> pd.DataFrame:
    """
    Returns a 1-row dataframe with columns like:
      p1_name, p1_team, ..., p5_chips
    """
    out: dict[str, object] = {}

    for r in ranks:
        pfx = prefix_map[r]  # e.g., "p1" or "p6"
        row = df.loc[df["rank"] == r]
        if row.empty:
            # Keep schema stable even if data missing
            for k in STAT_FIELDS:
                out[f"{pfx}_{k}"] = ""
            continue

        row = row.iloc[0]
        for k, col in STAT_FIELDS.items():
            out[f"{pfx}_{k}"] = row.get(col, "")

    return pd.DataFrame([out])


def main() -> None:
    if not WEB_TOP10_PATH.exists():
        raise FileNotFoundError(f"Missing {WEB_TOP10_PATH}. Run build_rankings first.")

    df = pd.read_csv(WEB_TOP10_PATH, encoding="utf-8")

    # Ensure rank is numeric
    df["rank"] = pd.to_numeric(df["rank"], errors="coerce").astype("Int64")
    df = df.dropna(subset=["rank"]).copy()
    df["rank"] = df["rank"].astype(int)

    # Top 5: ranks 1-5
    top5 = _flatten(
        df=df,
        ranks=[1, 2, 3, 4, 5],
        prefix_map={1: "p1", 2: "p2", 3: "p3", 4: "p4", 5: "p5"},
    )
    CANVA_TOP5_PATH.parent.mkdir(parents=True, exist_ok=True)
    top5.to_csv(CANVA_TOP5_PATH, index=False, encoding="utf-8")
    print(f"[SAVED] {CANVA_TOP5_PATH}")

    # 6-10: ranks 6-10
    six_ten = _flatten(
        df=df,
        ranks=[6, 7, 8, 9, 10],
        prefix_map={6: "p6", 7: "p7", 8: "p8", 9: "p9", 10: "p10"},
    )
    six_ten.to_csv(CANVA_6_10_PATH, index=False, encoding="utf-8")
    print(f"[SAVED] {CANVA_6_10_PATH}")


if __name__ == "__main__":
    main()
